[2025-03-09T01:04:34.328+0000] {processor.py:186} INFO - Started process (PID=4179) to work on /opt/airflow/dags/dag.py
[2025-03-09T01:04:34.329+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-09T01:04:34.331+0000] {logging_mixin.py:190} INFO - [2025-03-09T01:04:34.331+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-09T01:04:34.703+0000] {logging_mixin.py:190} INFO - [2025-03-09T01:04:34.698+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-09T01:04:34.705+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-09T01:04:34.727+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.402 seconds
[2025-03-09T01:05:05.188+0000] {processor.py:186} INFO - Started process (PID=4243) to work on /opt/airflow/dags/dag.py
[2025-03-09T01:05:05.188+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-09T01:05:05.190+0000] {logging_mixin.py:190} INFO - [2025-03-09T01:05:05.190+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-09T01:05:05.282+0000] {logging_mixin.py:190} INFO - [2025-03-09T01:05:05.277+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-09T01:05:05.283+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-09T01:05:05.302+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.118 seconds
[2025-03-09T01:05:35.889+0000] {processor.py:186} INFO - Started process (PID=4307) to work on /opt/airflow/dags/dag.py
[2025-03-09T01:05:35.890+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-09T01:05:35.892+0000] {logging_mixin.py:190} INFO - [2025-03-09T01:05:35.892+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-09T01:05:35.982+0000] {logging_mixin.py:190} INFO - [2025-03-09T01:05:35.978+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-09T01:05:35.983+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-09T01:05:35.997+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.112 seconds
[2025-03-09T01:06:06.511+0000] {processor.py:186} INFO - Started process (PID=4371) to work on /opt/airflow/dags/dag.py
[2025-03-09T01:06:06.512+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-09T01:06:06.514+0000] {logging_mixin.py:190} INFO - [2025-03-09T01:06:06.514+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-09T01:06:06.615+0000] {logging_mixin.py:190} INFO - [2025-03-09T01:06:06.611+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-09T01:06:06.616+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-09T01:06:06.636+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.131 seconds
[2025-03-09T01:06:36.866+0000] {processor.py:186} INFO - Started process (PID=4435) to work on /opt/airflow/dags/dag.py
[2025-03-09T01:06:36.866+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-09T01:06:36.869+0000] {logging_mixin.py:190} INFO - [2025-03-09T01:06:36.868+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-09T01:06:36.965+0000] {logging_mixin.py:190} INFO - [2025-03-09T01:06:36.962+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-09T01:06:36.966+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-09T01:06:36.983+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.122 seconds
[2025-03-09T01:07:07.175+0000] {processor.py:186} INFO - Started process (PID=4499) to work on /opt/airflow/dags/dag.py
[2025-03-09T01:07:07.175+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-09T01:07:07.178+0000] {logging_mixin.py:190} INFO - [2025-03-09T01:07:07.177+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-09T01:07:07.284+0000] {logging_mixin.py:190} INFO - [2025-03-09T01:07:07.280+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-09T01:07:07.286+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-09T01:07:07.305+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.135 seconds
[2025-03-09T01:07:37.531+0000] {processor.py:186} INFO - Started process (PID=4563) to work on /opt/airflow/dags/dag.py
[2025-03-09T01:07:37.532+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-09T01:07:37.533+0000] {logging_mixin.py:190} INFO - [2025-03-09T01:07:37.533+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-09T01:07:37.633+0000] {logging_mixin.py:190} INFO - [2025-03-09T01:07:37.629+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-09T01:07:37.634+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-09T01:07:37.654+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.128 seconds
[2025-03-09T01:08:07.824+0000] {processor.py:186} INFO - Started process (PID=4627) to work on /opt/airflow/dags/dag.py
[2025-03-09T01:08:07.825+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-09T01:08:07.827+0000] {logging_mixin.py:190} INFO - [2025-03-09T01:08:07.827+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-09T01:08:07.931+0000] {logging_mixin.py:190} INFO - [2025-03-09T01:08:07.927+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-09T01:08:07.932+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-09T01:08:07.956+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.137 seconds
[2025-03-09T01:08:38.555+0000] {processor.py:186} INFO - Started process (PID=4691) to work on /opt/airflow/dags/dag.py
[2025-03-09T01:08:38.556+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-09T01:08:38.558+0000] {logging_mixin.py:190} INFO - [2025-03-09T01:08:38.557+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-09T01:08:38.673+0000] {logging_mixin.py:190} INFO - [2025-03-09T01:08:38.668+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-09T01:08:38.675+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-09T01:08:38.700+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.152 seconds
[2025-03-09T01:09:08.987+0000] {processor.py:186} INFO - Started process (PID=4755) to work on /opt/airflow/dags/dag.py
[2025-03-09T01:09:08.988+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-09T01:09:08.989+0000] {logging_mixin.py:190} INFO - [2025-03-09T01:09:08.989+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-09T01:09:09.079+0000] {logging_mixin.py:190} INFO - [2025-03-09T01:09:09.076+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-09T01:09:09.080+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-09T01:09:09.103+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.121 seconds
